version: "2.4"
services:
  rtabmap_ros:
    build: "."
    image: "rtabmap_ros"
    network_mode: "host"
    runtime: "nvidia"
    ipc: "host"
    volumes:
      - /usr/lib/nvidia/:/usr/lib/nvidia/
      - /usr/lib/nvidia-450:/usr/lib/nvidia-450
      - /usr/lib32/nvidia-450:/usr/lib32/nvidia-450
      - /usr/lib/nvidia-430:/usr/lib/nvidia-430
      - /usr/lib32/nvidia-430:/usr/lib32/nvidia-430
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      DISPLAY: "$DISPLAY"
      QT_X11_NO_MITSHM: "1"
      ROS_MASTER_URI: "http://hsrb_eth.local:11311"
      ROS_IP: "10.0.0.115"
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: all
#    deploy:
#      resources:
#        reservations:
#          devices:
#            - capabilities:
#              - gpu
    command: bash 
    stdin_open: true
    tty: true
    privileged: true
